import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const content = `// Generated by scripts/set_feature_flags.js. Do not edit by hand.\n\n`;

const outPath = path.join(__dirname, "..", "src", "feature_flags.nr");
fs.writeFileSync(outPath, content, "utf8");

console.log("[feature_flags] no feature flags configured");
