import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const content = `// Generated by scripts/set_feature_flags.js. Do not edit by hand.\n\n// When true, use Noir's optimized MiMC (91 rounds, exponent 7)\n// When false, use Dark Forest's original MiMC (220 rounds, exponent 5)\n// NOTE: Changing this creates a different game universe with different location IDs!\npub global USE_AZTEC_MIMC: bool = true;\n`;

const outPath = path.join(__dirname, "..", "src", "feature_flags.nr");
fs.writeFileSync(outPath, content, "utf8");

console.log("[feature_flags] no feature flags configured");
