import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rawAdmin = process.env.DF_ENABLE_ADMIN_ACTIONS;
const adminEnabled = rawAdmin === undefined
    ? true
    : !["0", "false", "off", "no"].includes(rawAdmin.toLowerCase());

const content = `// Generated by scripts/set_feature_flags.js. Do not edit by hand.\n\n` +
    `pub global ADMIN_ACTIONS_ENABLED: bool = ${adminEnabled ? "true" : "false"};\n`;

const outPath = path.join(__dirname, "..", "src", "feature_flags.nr");
fs.writeFileSync(outPath, content, "utf8");

const status = adminEnabled ? "enabled" : "disabled";
console.log(`[feature_flags] admin actions ${status}`);
